global_costmap:
  global_frame: /map
  robot_base_frame: base_link
  resolution: 0.2
  rolling_window:             false
  track_unknown_space:        true
  width:                      60.0  #150
  height:                     60.0  #150
  origin_x:                   -30   #-75
  origin_y:                   -30   #-75
  static:                     true

  plugins:
     - {name: static,                    type: "costmap_2d::StaticLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
