TebLocalPlannerROS:
  odom_topic: odom
  map_frame: /map

  # Trajectory
  dt_hysteresis: 0.03
  dt_ref: 0.2
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 6.0
  feasibility_check_no_poses: 5
  allow_init_with_backwards_motion: false
  exact_arc_length: false
  publish_feedback: false
  force_reinit_new_goal_dist: 1.0
  global_plan_viapoint_sep: 0.7
  feasibility_check_no_poses: 5
  shrink_horizon_backup: true








  # Robot
  max_vel_theta: 2.0
  max_vel_x: 0.5
  max_vel_x_backwards: 0.2
  max_vel_y: 0.0
  acc_lim_theta: 3.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  min_turning_radius: 0.0
  cmd_angle_instead_rotvel: false
  footprint_model:
    type: "polygon"
    vertices: [ [0.3602, -0.0708], [0.274, -0.0708], [0.274, -0.254], [-0.274, -0.274], [-0.274, 0.274], [0.274, 0.274], [0.274, 0.0708], [0.3602, 0.0708] ]

  # GoalTolerance
  xy_goal_tolerance: 1.5
  yaw_goal_tolerance: 2.0
  free_goal_vel: false

  # Obstacles
  min_obstacle_dist: 0.3
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 30
  inflation_dist: 0.6
  legacy_obstacle_association: false
  obstacle_association_cutoff_factor: 5.0
  obstacle_association_force_inclusion_factor: 1.5
  # Obstacles Converter
  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  costmap_converter/CostmapToPolygonsDBSConcaveHull:
     cluster_max_distance: 0.4
     cluster_min_pts: 2
     cluster_max_pts: 30
     convex_hull_min_pt_separation: 0.1
     concave_hull_depth: 1.0





  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_acc_lim_theta: 50.0
  weight_acc_lim_x: 10.0
  weight_acc_lim_y: 1.0
  weight_adapt_factor: 2.0
  weight_dynamic_obstacle: 50.0
  weight_dynamic_obstacle_inflation: 0.1
  weight_inflation: 10.0
  weight_kinematics_forward_drive: 5.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_turning_radius: 90.0
  weight_max_vel_theta: 50.0
  weight_max_vel_x: 5.0
  weight_max_vel_y: 2.0
  weight_obstacle: 50.0
  weight_optimaltime: 10.0
  weight_viapoint: 8.0

  # Homotopy Class Planner
  enable_multithreading: true
  max_number_classes: 4
  roadmap_graph_area_length_scale: 1.0
  roadmap_graph_area_width: 5.0
  roadmap_graph_no_samples: 15
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
  selection_alternative_time_cost: false
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 1.0
  viapoints_all_candidates: true
