local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 8.4
  height: 8.4
  resolution: 0.12
  plugins:
     - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
     - {name: inflation,                 type: "costmap_2d::InflationLayer"}
